name: Update Economic Data
on:
  schedule:
    # 毎週月曜日の午前3時(UTC)に実行
    - cron: '0 3 * * 1'
  # 手動実行用のトリガー
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run BOJ data download scripts
      run: |
        python scripts/get_boj_unsecured_call_rate.py
        python scripts/get_boj_corporate_price_index.py
        
    - name: Run CPI data download and processing scripts
      run: |
        python scripts/get_cpi.py
        python scripts/process_cpi.py
        
    - name: Run Payroll data download and processing scripts
      run: |
        python scripts/get_payroll.py
        python scripts/process_payroll.py
        
    - name: Run Real Estate data download and processing
      run: |
        python scripts/get_real_estate.py
        python scripts/process_real_estate.py
        
    - name: Run DI data download and processing
      run: |
        python scripts/get_di.py
        python scripts/process_di.py
        
    - name: Run FRED GDP data download and processing
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: |
        python scripts/get_fred_gdp.py
        
    - name: List files in data directory
      run: |
        ls -la data/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: economic-data
        path: |
          data/*.csv
          data/*.xlsx
        retention-days: 7
        
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*.csv data/*.xlsx
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update economic data $(date +'%Y-%m-%d')" && git push)